# Generated by Django 2.1 on 2018-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180822_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ans',
            field=models.CharField(default='only admin knows the ans', max_length=300),
        ),
    ]
