# Generated by Django 2.1 on 2018-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_account_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemCost', models.IntegerField()),
                ('itemDesc', models.CharField(max_length=1000)),
                ('itemRat', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='ans',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='NULL', max_length=500),
        ),
    ]
