# Generated by Django 2.1 on 2018-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_item_itempic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemCost',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemRat',
            field=models.CharField(max_length=1),
        ),
    ]
