# Generated by Django 2.1 on 2018-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180903_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv',
            name='order1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='order2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='order3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='order4',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='order5',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
