# Generated by Django 2.1 on 2018-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20180906_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemType',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
